### ISSUE TITLE
How can I route Wireguard server through another VPN?

### ISSUE THREAD

**Issue by schklom** [linuxserver/docker-wireguard#108]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Wireguard: `network_mode: service:vpn`
------------------------------

## Expected Behavior

Phone should connect to Internet via Wireguard server+VPN: Phone -> Wireguard server -> VPN container -> Internet.
## Current Behavior

Phpne has no internet when connected to Wireguard server.
## Steps to Reproduce

1.Set `net.ipv4.ip_forward=1`
2.Install Rootless Docker
3.`docker-compose up -d`

## Environment
**OS:** Debian 10
**CPU architecture:** arm64
**How docker service was installed:** [Official Rootless docker repo](https://docs.docker.com/engine/security/rootless/#install) without packages: `curl -fsSL https://get.docker.com/rootless | sh`

The Wireguard server works well without routing through the other VPN.
## Command used to create docker container (run/create/compose/screenshot)

```
version: "3.8"
services:
  vpn:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - USER=${NORDVPN_USERNAME}
      - PASS=${NORDVPN_PASSWORD}
      - CONNECT=${NORDVPN_CONNECT}
      - TECHNOLOGY=NordLynx
      - TZ=${TZ}
      # CIDR networks (IE 192.168.1.0/24), add a route to allows replies once the VPN is up.
      - NETWORK=10.13.13.0/24
      # Semicolon delimited list of ports to whitelist for both UDP and TCP
      - PORTS=51820
    ports:
      - 51820:51820/udp

  wireguard_vpn:
    image: ghcr.io/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 0
      PGID: 0
      TZ: ${TZ}
      SERVERURL: ${URL}
      PEERS: tel
    depends_on:
      - vpn
    network_mode: service:vpn
    volumes:
      - ${DOCKERCONFIG}/wireguard_vpn:/config
      - /lib/modules:/lib/modules:ro
```
## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Uname info: Linux vpn 5.10.0-0.bpo.5-arm64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) aarch64 aarch64 aarch64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Server mode is selected ****
**** External server address is set to <MY_DOMAIN> ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0, ::/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** Server mode is selected ****
**** No changes to parameters. Existing configs are used. ****
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.19/32 dev wg0
.:53
CoreDNS-1.8.3
linux/arm64, go1.16, 4293992
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```
