### ISSUE TITLE
Volumes Files Have Root Owner when Running Container with Non-Root User

### ISSUE THREAD

**Issue by norsemanGrey** [linuxserver/docker-wireguard#116]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I am using the PUIG and PGUID variables when creating the containers and assumed that the files (in /config) created by the container application should have corresponding owners. This is the behaviors with other LSIO containers I am running on the same system.

## Current Behavior

Files created by the container in /config are created with root owner.

## Steps to Reproduce

1. Create docker-compose file with PUID / PGID. (non-root user and docker group IDs)
2. Start container.
3. Check files in /config bind mount location.

## Environment
**OS:** Ubuntu Server 20.04 w/Docker install from official repo.

## Command used to create docker container (run/create/compose/screenshot)

```
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PIA_AUTOCONNECT=wireguard
    networks:
      docker_net:
    ports:
      - target: 51820
        published: 51820
        protocol: udp
    sysctls:
      # Set IPv4 and IPv6 parameters.
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    volumes:
      - type: bind
        source: ${DIR_DOCKER}/wireguard/config
        target: /config
      - type: bind
        source: /lib/modules
    restart: unless-stopped

```

## Logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[env-init] PIA_PASS set from FILE__PIA_PASS
[env-init] PIA_USER set from FILE__PIA_USER
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    998
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux 3bdb2ad41178 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Client mode selected. ****
**** Disabling CoreDNS ****
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] files found in /config/custom-cont-init.d executing
[custom-init] 00-setup-wireguard: executing...
[custom-init] 00-setup-wireguard: exited 0
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Warning: `/config/wg0.conf' is world accessible
```
