### ISSUE TITLE
SERVERPORT option not working

### ISSUE THREAD

**Issue by bikeymouse** [linuxserver/docker-wireguard#117]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I'm using the  option  SERVERPORT=51830 in the docker-compose file to change the default listen-port.
I also used port commands to map this outside the container.
However WireGuard is not reachable on the configured port.

## Current Behavior

After starting up a config file is created  with the default port (51820)
It also reports this in the log:
*** External server port is set to 51830. Make sure that port is properly forwarded to port 51820 inside this container ****
## Steps to Reproduce

1. Removed the config file (wg0.conf) and restarted the container
2. Changed ListenPort in the config file manually to 51830 after which things worked as expected.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
Linux b6cc2e86c719 4.19.0-16-amd64 #1 SMP 
Debian 4.19.181-1 (2021-03-19) x86_64 x86_64 x86_64 GNU/Linux

**How docker service was installed:**

From official docker repo using docker-compose
## Command used to create docker container (run/create/compose/screenshot)

```
version: '3.8'
services:
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SERVERURL=***
      - SERVERPORT=51830
      - PEERS=***,***
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.0.0.0
    ports:
      - 51830:51830/udp
    volumes:
      - type: bind
        source: ./config/
        target: /config/
      - type: bind
        source: /lib/modules
        target: /lib/modules
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
```
## Docker logs

```
Attaching to wireguard
wireguard    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
wireguard    | [s6-init] ensuring user provided files have correct perms...exited 0.
wireguard    | [fix-attrs.d] applying ownership & permissions fixes...
wireguard    | [fix-attrs.d] done.
wireguard    | [cont-init.d] executing container initialization scripts...
wireguard    | [cont-init.d] 01-envfile: executing... 
wireguard    | [cont-init.d] 01-envfile: exited 0.
wireguard    | [cont-init.d] 10-adduser: executing... 
wireguard    | usermod: no changes
wireguard    | 
wireguard    | -------------------------------------
wireguard    |           _         ()
wireguard    |          | |  ___   _    __
wireguard    |          | | / __| | |  /  \ 
wireguard    |          | | \__ \ | | | () |
wireguard    |          |_| |___/ |_|  \__/
wireguard    | 
wireguard    | 
wireguard    | Brought to you by linuxserver.io
wireguard    | -------------------------------------
wireguard    | 
wireguard    | To support the app dev(s) visit:
wireguard    | WireGuard: https://www.wireguard.com/donations/
wireguard    | 
wireguard    | To support LSIO projects visit:
wireguard    | https://www.linuxserver.io/donate/
wireguard    | -------------------------------------
wireguard    | GID/UID
wireguard    | -------------------------------------
wireguard    | 
wireguard    | User uid:    1000
wireguard    | User gid:    1000
wireguard    | -------------------------------------
wireguard    | 
wireguard    | [cont-init.d] 10-adduser: exited 0.
wireguard    | [cont-init.d] 30-config: executing... 
wireguard    | Uname info: Linux b6cc2e86c719 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 x86_64 x86_64 GNU/Linux
wireguard    | **** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
wireguard    | **** Server mode is selected ****
wireguard    | **** External server address is set to **** ****
wireguard    | **** External server port is set to 51830. Make sure that port is properly forwarded to port 51820 inside this container ****
wireguard    | **** Internal subnet is set to 10.0.0.0 ****
wireguard    | **** AllowedIPs for peers 0.0.0.0/0, ::/0 ****
wireguard    | **** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.0.0.1 to use wireguard docker host's DNS. ****
wireguard    | **** No wg0.conf found (maybe an initial install), generating 1 server and ***,*** peer/client confs **
**** QR codes ****
wireguard    | [cont-init.d] 30-config: exited 0.
wireguard    | [cont-init.d] 99-custom-scripts: executing... 
wireguard    | [custom-init] no custom files found exiting...
wireguard    | [cont-init.d] 99-custom-scripts: exited 0.
wireguard    | [cont-init.d] done.
wireguard    | [services.d] starting services
wireguard    | [services.d] done.
wireguard    | Warning: `/config/wg0.conf' is world accessible
wireguard    | [#] ip link add wg0 type wireguard
wireguard    | [#] wg setconf wg0 /dev/fd/63
wireguard    | .:53
wireguard    | CoreDNS-1.8.4
wireguard    | linux/amd64, go1.16.4, 053c4d5
wireguard    | [#] ip -4 address add 10.0.0.1 dev wg0
wireguard    | [#] ip link set mtu 1420 up dev wg0
wireguard    | [#] ip -4 route add 10.0.0.3/32 dev wg0
wireguard    | [#] ip -4 route add 10.0.0.2/32 dev wg0
wireguard    | [#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```
