### ISSUE TITLE
SERVER_ALLOWEDIPS_PEER_ does not work

### ISSUE THREAD

**Issue by master-hax** [linuxserver/docker-wireguard#143]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

the `SERVER_ALLOWEDIPS_PEER_` to add additional allowed subnets for a specific peer does not work, the peer conf is generated with the default `ALLOWEDIPS` subnet.
------------------------------

## Expected Behavior

`SERVER_ALLOWEDIPS_PEER_` should add a subnet to the peer's `wg0.conf` file

## Current Behavior

`SERVER_ALLOWEDIPS_PEER_` does not work & the peer's `wg0.conf` is generated without the additional subnet

## Steps to Reproduce

1. use `SERVER_ALLOWEDIPS_PEER_` in your compose file
2. start the container with a fresh `/config` directory to generate confs
3. all peers are generated with the default server allowed IPs & the extra subnets are not added

## Environment
**OS:** DietPi
**CPU architecture:**arm64
**How docker service was installed:**

dunno

## Command used to create docker container (run/create/compose/screenshot)

```
  vpn-server:
    image: lscr.io/linuxserver/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=65536
      - SERVERURL=server.home.net
      - SERVERPORT=51820
      - PEERDNS=auto
      - INTERNAL_SUBNET=100.64.1.0
      - ALLOWEDIPS=100.64.1.1/32
      - PEERS=fullvpn,partialvpn,dnsonly
      - SERVER_ALLOWEDIPS_PEER_fullvpn="0.0.0.0/0"          # these work fine when edited into the confs manually
      - SERVER_ALLOWEDIPS_PEER_partialvpn="10.0.0.0/16" # these work fine when edited into the confs manually
      # - SERVER_ALLOWEDIPS_PEER_dnsonly="100.64.1.1/32" # these work fine when edited into the confs manually
    volumes:
      - /lib/modules:/lib/modules
      - wireguard-server-data-volume:/config
    ports:
      - 51820:51820/udp
```

## Docker logs

potentially relevant bit
```
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
Unable to parse IP address: `"0.0.0.0'
Configuration parsing error
[#] ip link delete dev wg0
.:53
CoreDNS-1.8.7
linux/arm64, go1.17.6, a9adfd5
```
