### ISSUE TITLE
 RTNETLINK answers: Operation not supported

### ISSUE THREAD

**Issue by rickdgit** [linuxserver/docker-wireguard#149]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Im trying to run this container on Synology with docker managed by Portainer

I follow the docker-compose file to create the stack and this is what I got from the log:

```
RTNETLINK answers: Operation not supported,
Uname info: Linux d2d1f90c8b29 4.4.180+ #42218 SMP Mon Oct 18 19:16:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux,
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
```

Also it can not download the headers : 

```
RTNETLINK answers: Operation not supported,
Uname info: Linux d2d1f90c8b29 4.4.180+ #42218 SMP Mon Oct 18 19:16:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux,
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****,
Fetched 39.1 MB in 6s (6,127 kB/s),
Reading package lists...,
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****,
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****
```

I also tried download the headers by my self:

```
root@d2d1f90c8b29:/# apt install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-4.4.180
E: Couldn't find any package by glob 'linux-headers-4.4.180'
E: Couldn't find any package by regex 'linux-headers-4.4.180'
```

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:** Synology DSM7 
**CPU architecture:** Intel Celeron J4125 x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

```

---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=mydomain.com #optional
      - SERVERPORT=50000 #optional
      #- PEERS=3 #optional
      #- PEERDNS=auto #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ${ROOT_PATH}/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 50000:50000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

## Docker logs

[_wireguard_logs.txt](https://github.com/linuxserver/docker-wireguard/files/8063421/_wireguard_logs.txt)

attached
