### ISSUE TITLE
Container has no internet access

### ISSUE THREAD

**Issue by diericx** [linuxserver/docker-wireguard#15]
Hi,
I'm trying to get a container booted up running Wireguard but can't seem to get this working. It works perfectly on the host, but not with this docker image so there is some discrepancy. 

------------------------------

## Expected Behavior
Container should boot with connection to wireguard and internet access.

## Current Behavior
Container will boot and successfully connect to my server, but when I go into it there is no internet access.

## Steps to Reproduce
1. Run the container with docker compose

## Environment
**OS:**  Ubuntu 18.04
**CPU architecture:** x86_64      
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
Using this docker-compose
```
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /etc/wireguard/wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
```

And this wg0 config, which works perfectly fine on my host.

```
[Interface]
PrivateKey = xxx
Address = 10.66.66.2/24
DNS = 176.103.130.130,176.103.130.131

[Peer]
PublicKey = xxx
PresharedKey = xxx
Endpoint = xxx:49161
AllowedIPs = 0.0.0.0/0,::/0
```

## Docker logs
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Hit:1 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
linux-headers-5.3.0-46-generic is already the newest version (5.3.0-46.38~18.04.1).
wireguard is already the newest version (1.0.20200319-0ppa1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Client mode selected.
/var/run/s6/etc/cont-init.d/30-config: line 163: [: !-f: unary operator expected
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Warning: `/config/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
.:53
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.66.66.2/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a tun.wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -6 route add ::/0 dev wg0 table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] ip6tables-restore -n
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: setting key "net.ipv4.conf.all.src_valid_mark": Read-only file system
[#] iptables-restore -n
````

Now from within the container I can see that it's connected succesfully:

```
root@6dfe0bd8e859:/# wg
interface: wg0
  public key: xxx
  private key: (hidden)
  listening port: 32881
  fwmark: 0xca6c

peer: xxx
  preshared key: (hidden)
  endpoint: xxx:49161
  allowed ips: 0.0.0.0/0
  latest handshake: 2 minutes, 43 seconds ago
  transfer: 124 B received, 532 B sent
```

but no internet access

```
root@6dfe0bd8e859:/# curl ifconfig.me
curl: (6) Could not resolve host: ifconfig.me
```
