### ISSUE TITLE
Configs not being created / Connection issues

### ISSUE THREAD

**Issue by angelfor3v3r** [linuxserver/docker-wireguard#162]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I should get configs created properly and be able to connect to wireguard. This seems to happen on any version after `v1.0.20210914-ls47` for me.

## Current Behavior

I only get a single config (the first name in the delimited `PEER_DNS` string) and cannot connect.

## Steps to Reproduce

1. Create a container with a version higher than
2. Run the container.
3. Connect to the Wiregaurd.

## Environment
**OS:** Debian GNU/Linux 11 (bullseye) (5.10.0-13-amd64)
**CPU architecture:** x86_64
**How docker service was installed:** From the official docker repo using apt.

## Command used to create docker container (run/create/compose/screenshot)

```
version: "3.9"
services:
    wireguard:
        #image: "linuxserver/wireguard:v1.0.20210914-ls62"
        image: "linuxserver/wireguard:v1.0.20210914-ls47"
        container_name: "wireguard"
        restart: "unless-stopped"
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=US/Eastern
            # - SERVERURL=[REDACTED]
            - SERVERURL=[REDACTED]
            - SERVERPORT=51820
            - PEERS="foo,public"
            - PEERDNS=auto
        ports:
            - "51820:51820/udp"
            - "51820:51820/tcp"
        volumes:
            - "/docker/data/wireguard:/config"
            - "/lib/modules:/lib/modules"
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1

networks:
    default:
        driver: "bridge"
        ipam:
            config:
                 - subnet: "172.31.0.0/16"
```

## Docker logs

I do notice these two lines in the logs below:
```
grep: /config/peer*/*.conf: No such file or directory
/var/run/s6/etc/cont-init.d/40-confs: line 54: SERVER_ALLOWEDIPS_PEER_"foo: invalid variable name
```

`linuxserver/wireguard:v1.0.20210914-ls62` logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-module: executing... 
Uname info: Linux dd5b87cf692e 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
[cont-init.d] 30-module: exited 0.
[cont-init.d] 40-confs: executing... 
**** Server mode is selected ****
**** External server address is set to 104.219.232.126 ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0, ::/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** No wg0.conf found (maybe an initial install), generating 1 server and "foo,public" peer/client confs ****
grep: /config/peer*/*.conf: No such file or directory
/var/run/s6/etc/cont-init.d/40-confs: line 54: SERVER_ALLOWEDIPS_PEER_"foo: invalid variable name
[cont-init.d] 40-confs: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
.:53
CoreDNS-1.9.1
linux/amd64, go1.17.8, 4b597f8
```

`v1.0.20210914-ls47` logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux e97ebe827754 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Server mode is selected ****
**** External server address is set to 104.219.232.126 ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0, ::/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** No wg0.conf found (maybe an initial install), generating 1 server and "foo,public" peer/client confs ****
grep: /config/peer*/*.conf: No such file or directory
PEER "foo QR code:
[REDACTED]
PEER public" QR code:
[REDACTED]
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.3/32 dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
.:53
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
```
