### ISSUE TITLE
Peers with dashes in their names aren't added to wg0.conf

### ISSUE THREAD

**Issue by adrian154** [linuxserver/docker-wireguard#167]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Peer names with dashes in them should function normally.

## Current Behavior
Attempting to start the container with `PEERS=invalid-name` yields:

```
/var/run/s6/etc/cont-init.d/40-confs: line 54: SERVER_ALLOWEDIPS_PEER_invalid-name: bad substitution
```

Keys and a client configuration are generated for the peer, but it fails to be included in wg0.conf and thus can't connect to the server.

## Steps to Reproduce

1. Start the container with `PEERS` set to a list of peer names where one of them includes a dash.
2. The error can be confirmed by checking wg0.conf or viewing the container's logs.

## Environment
**OS:** Linux 5.4.0-109-generic
**CPU architecture:** x86_64
**How docker service was installed:** Machine was provisioned using DigitalOcean's [Docker disk image](https://marketplace.digitalocean.com/apps/docker)

## Command used to create docker container (run/create/compose/screenshot)

```
  wireguard:
    image: lscr.io/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=America/Los_Angeles
      - PEERS=phone,desktop,laptop,hplaptop,invalid-name
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=10.0.0.0/8
    volumes:
      - /srv/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

## Docker logs

[Logs](https://gist.github.com/adrian154/4b0d40b85a0e6f05cc937f271d837919)

I modified the log manually to remove the client config qr codes for privacy purposes.
