### ISSUE TITLE
non-default server port fails to connect

### ISSUE THREAD

**Issue by freefly42** [linuxserver/docker-wireguard#171]
Specifying a server port other than the default in a docker-compose file results in the peers sending packets to the proper server port, but the server still listens on the default port, resulting in no connection.

Snip from docker-compose.yml:
```
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERURL=wireguard.sustaeon.com #optional
      - SERVERPORT=51822 #optional
      - PEERS=xxxx
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.43.43.0 #optional
      - ALLOWEDIPS=10.43.43.0/24
    volumes:
      - 'config:/config'
      - /lib/modules:/lib/modules
    ports:
      - 51822:51822/udp
```

Resulting wg0.conf:
```
[Interface]
Address = 10.43.43.1
ListenPort = 51820
PrivateKey = xxxxxx
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```
The fix is to hand edit the config/templates/server.conf to put the right port in ListenPort (default is it will have 51820):
```
[Interface]
Address = ${INTERFACE}.1
ListenPort = 51822
PrivateKey = $(cat /config/server/privatekey-server)
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```
Delete the wg0.conf and respin the container, at which point the wg0.conf will have the correct port.
