### ISSUE TITLE
Current server template does not allow to change wireguard server port

### ISSUE THREAD

**Issue by Megum1n** [linuxserver/docker-wireguard#172]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Wireguard server is starting with a port specified as `SERVERPORT` environment variable.

## Current Behavior
Wireguard server is starting with a default port from [template file](https://github.com/linuxserver/docker-wireguard/blob/master/root/defaults/server.conf#L3) (51820).

## Steps to Reproduce
1. Set `SERVERPORT=51821` environment variable for docker container

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** x86_64
**How docker service was installed:** official docker repo (get.docker.com script)

## Command used to create docker container (run/create/compose/screenshot)
```yaml
---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERPORT=51821
      - PEERS=1
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51821:51821/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

## Docker logs
No need
