### ISSUE TITLE
wg0 interface is hard coded. Cannot run multiple instances or on system that already runs wireguard.

### ISSUE THREAD

**Issue by michaelkrieger** [linuxserver/docker-wireguard#179]
The wg0 interface is hardcoded in various scripts.  As such, if wg0 is already in use on the system, it throws an error and will never work correctly.

------------------------------

## Expected Behavior
docker-wireguard should find the next unused interface (ie: wg1) and use it throughout its setup, routing, etc.

## Current Behavior
docker writeguard throws a `wg-quick: wg0 already exists` error in its logs and never properly configures.
Looking at the interface (by running `ip addr` or any other similar command in the wireguard container) shows configuration made by the other wireguard instance.

## Steps to Reproduce
Have another wireguard interface on the system in question
Start docker-wireguard

## Environment
**OS:** Debian 11
**CPU architecture:** x86_64
**How docker service was installed:** Docker rep

## Command used to create docker container (run/create/compose/screenshot)
```
  wireguard-vpn:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-vpn
    cap_add:
- NET_ADMIN
- SYS_MODULE
    environment:
- PUID=1000
- PGID=1000
- TZ=America/Toronto
- SERVERURL=192.168.1.39
- SERVERPORT=51821 #optional
- PEERS=me
- PEERDNS=auto #optional
- INTERNAL_SUBNET=10.26.13.0 #optional
- ALLOWEDIPS=0.0.0.0/0 #optional
- LOG_CONFS=true #optional
    network_mode: service:otherwireguardcontainer
    volumes:
- /srv/wireguard-vpn:/config
- /lib/modules:/lib/modules
    #ports:
    #  - 51821:51820/udp
    sysctls:
- net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

## Docker logs
```
rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-module
Uname info: Linux 420b0f153d7e 5.18.0-0.bpo.1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1~bpo11+1 (2022-06-14) x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
cont-init: info: /etc/cont-init.d/30-module exited 0
cont-init: info: running /etc/cont-init.d/40-confs
**** Server mode is selected ****
**** External server address is set to 192.168.1.39 ****
**** External server port is set to 51821. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.26.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.26.13.1 to use wireguard docker host's DNS. ****
**** Server mode is selected ****
**** No changes to parameters. Existing configs are used. ****
cont-init: info: /etc/cont-init.d/40-confs exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-scripts
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-scripts exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun coredns (no readiness notification)
services-up: info: copying legacy longrun wireguard (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
wg-quick: `wg0' already exists
.:53
CoreDNS-1.9.3
linux/amd64, go1.18.2, 45b0a11
s6-rc: info: service 99-ci-service-check: stopping
s6-rc: info: service 99-ci-service-check successfully stopped
s6-rc: info: service legacy-services: stopping
Caught SIGTERM signal!
[INFO] SIGTERM: Shutting down servers then terminating
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service 00-legacy: stopping
s6-rc: info: service 00-legacy successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
Terminated
Caught SIGTERM signal!
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
[#] iptables-restore -n
[#] iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
iptables: Bad rule (does a matching rule exist in that chain?).
```
