### ISSUE TITLE
Wireguard only works when disabling UFW?

### ISSUE THREAD

**Issue by BrodyStone21** [linuxserver/docker-wireguard#187]
Hello, I'm working on moving everything from docker run to docker-compose. Getting Wireguard set up again is proving to be quite difficult for me. I'm running Ubuntu 22.04 LTS 64-bit. Everything is up to date. 

With UFW enabled, I can see a handshake has been completed, I can see DNS requests within Pi-hole, and I can access things on LAN. However, I'm unable to access any public websites. The DNS resolution is not working. If I disable UFW, this problem goes away. I believe this is something to do with my wg0.conf file, but I'm unable to nail down exactly what.

I've tried running `sudo ufw allow 51825/udp` and restarting UFW, but that doesn't solve my issue. Any input here would be appreciated. 

```
version: '3'

services:
  unbound:
    container_name: unbound
    restart: unless-stopped
    image: klutchell/unbound
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/ubuntu/.config/unbound/unbound.conf:/etc/unbound/custom.conf.d/unbound.conf
      - /home/ubuntu/.config/unbound/root.hints:/etc/unbound/root.hints
    network_mode: host
  pihole:
    container_name: pihole
    restart: unless-stopped
    image: pihole/pihole
    cap_add:
      - NET_ADMIN
    environment:
      - FTLCONF_REPLY_ADDR4=192.168.1.2
      - INTERFACE=enp5s0
      - TZ=America/Indianapolis
      - WEBPASSWORD=REDACTED
      - PIHOLE_DNS="127.0.0.1#5053;127.0.0.1#5053"
      - DHCP_ACTIVE=true
      - DHCP_START=192.168.1.3
      - DHCP_END=192.168.1.254
      - DHCP_ROUTER=192.168.1.1
      - DHCP_LEASETIME=24
      - DHCP_IPV6=false
      - DHCP_rapid-commit=false
      - DNSMASQ_LISTENING=all
      - DNSSEC=false
      - CUSTOM_CACHE_SIZE=0
    volumes:
      - /home/ubuntu/.config/pihole:/etc/pihole
      - /home/ubuntu/.config/pihole/dnsmasq.d:/etc/dnsmasq.d
    network_mode: host
    depends_on:
      - unbound
  wireguard:
    container_name: wireguard
    restart: unless-stopped
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - SERVERPORT=51825
      - SERVERURL=REDACTED
      - PEERS=1,2,3,4,5
      - PEERDNS=192.168.1.2
      - INTERNAL_SUBNET=10.15.15.0
      - LOG_CONFS=true
    volumes:
      - /mnt/WD_White/Server_Stuff/Wireguard:/config
      - /lib/modules:/lib/modules
    depends_on:
      - pihole
    network_mode: host
```

```
[Interface]
Address = 10.15.15.1
ListenPort = 51825
PrivateKey = REDACTED=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o enp5s0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o enp5s0 -j MASQUERADE

[Peer]
# peer1
PublicKey = REDACTED=
PresharedKey = REDACTED=
AllowedIPs = 10.15.15.2/32
```
