### ISSUE TITLE
CoreDNS is not disabled in client mode

### ISSUE THREAD

**Issue by Skywrtr** [linuxserver/docker-wireguard#190]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Core DNS should be optional in client mode, e.g. when using `network_mode: host`.

## Current Behavior

The container starts a CoreDNS instance on port 53, which – in this networking mode – is the host port.
In the container version v1.0.20210914-ls81 everything works. In version v1.0.20210914-ls82 something broke

## Steps to Reproduce

1. Use the container in client mode with `network_mode: host`

## Environment
**OS: Linux**
**CPU architecture:** arm64
**How docker service was installed:  20.10.12**

## Command used to create docker container (run/create/compose/screenshot)

```
 wireguard:
    image: linuxserver/wireguard:v1.0.20210914-ls81
    container_name: wireguard
    restart: unless-stopped
    network_mode: host
    volumes:
      - './wireguard:/config'
      - '/lib/modules:/lib/modules:ro'
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TZ         
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
```
## Docker logs

`Another service is using port 53, disabling CoreDNS`
