### ISSUE TITLE
curl no longer works within container

### ISSUE THREAD

**Issue by derekoharrow** [linuxserver/docker-wireguard#195]
Using curl within the docker container no longer works.

Curl is often used, as in my case, as part of a healthcheck routine to make sure the wireguard connection is up and running. This is now failing.

------------------------------

## Expected Behavior
curl should work as expected and return the contents of a webpage - e.g. curl ifconfig.me should return my public IP address.

## Current Behavior
Fails with

`curl: (6) getaddrinfo() thread failed to start
`

## Steps to Reproduce
1. docker exec -it wireguard bash
2. curl ifconfig.me

The VPN connection is established fine and I have external access - it's just curl that fails:

```
wg

interface: wg0
  public key: XXXXXXXXXXXXXXXXXXXXXXXXX
  private key: (hidden)
  listening port: 51820
  fwmark: 0xca6c

peer: XXXXXXXXXXXXXXXXXXXXXXXXX=
  endpoint: 37.120.153.2:1443
  allowed ips: 0.0.0.0/0
  latest handshake: 13 seconds ago
  transfer: 181.47 KiB received, 173.12 KiB sent
  persistent keepalive: every 25 seconds

ping google.com
PING google.com (142.250.187.206) 56(84) bytes of data.
64 bytes from lhr25s33-in-f14.1e100.net (142.250.187.206): icmp_seq=1 ttl=59 time=79.0 ms
64 bytes from lhr25s33-in-f14.1e100.net (142.250.187.206): icmp_seq=2 ttl=59 time=76.1 ms
```

## Environment
**OS:** Ubuntu 20.04.2 LTS
**CPU architecture:** x86_64
**How docker service was installed:** From image: ghcr.io/linuxserver/wireguard 

## Command used to create docker container (run/create/compose/screenshot)
```
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    ports:
      - 51820:51820/udp
    volumes:
      - /data/appdata/docker/wireguard:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/config/healthcheck.sh"]
      interval: 2m
      timeout: 10s
      retries: 3
```

## Docker logs
```



-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    117
-------------------------------------

Uname info: Linux wireguard 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Client mode selected. ****
**** Disabling CoreDNS ****
[custom-init] No custom files found, skipping...
Warning: `/config/wg0.conf' is world accessible
[ls.io-init] done.
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.128.93/24 dev wg0
[#] ip link set mtu 1292 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: setting key "net.ipv4.conf.all.src_valid_mark", ignoring: Read-only file system
[#] iptables-restore -n
[#] DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route add $HOMENET3 via $DROUTE;ip route add $HOMENET2 via $DROUTE; ip route add $HOMENET via $DROUTE;iptables -I OUTPUT -d $HOMENET -j ACCEPT;iptables -A OUTPUT -d $HOMENET2 -j ACCEPT; iptables -A OUTPUT -d $HOMENET3 -j ACCEPT;  iptables -A OUTPUT ! -o wg0 -m mark ! --mark $(wg show wg0 fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
.:53
CoreDNS-1.10.0
linux/amd64, go1.19.1, 596a9f9
Caught SIGTERM signal!
Warning: `/config/wg0.conf' is world accessible
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
[#] resolvconf -d wg0 -f
[#] iptables-restore -n
[INFO] SIGTERM: Shutting down servers then terminating
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
usermod: no changes
```
