### ISSUE TITLE
Problems with wireguard using my own unbound in Docker

### ISSUE THREAD

**Issue by rucksman** [linuxserver/docker-wireguard#200]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I would expect the PEERDNS to work. At the moment my internal hosts which are defined in unbound.conf cannot be reached via wireguard.

## Current Behavior
I cannot reach my internal hosts, name resolution does not work.

## Steps to Reproduce

Wireguard and Unbound are running in Docker containers on the same host. Unbound is working fine with all the other containers and throughout my internal network. It also works with OpenVPN. No matter if I set PEERDNS to auto or to the IP address of the host or the IP address of the Unbound container, name resolution is not possible. I installed Wireguard on a different machine (no docker) for testing purposes, and when I enter the host IP of the machine where the Unbound container is running into the client config, everything works fine. So there is a problem somewhere with DNS in your image, at least in combination with my local Unbound container.

## Environment
**OS:** Ubuntu Server 18.04 LTS
**CPU architecture:** x86_64
**How docker service was installed:**
From Docker repo

## Command used to create docker container (run/create/compose/screenshot)
```
version: '2.1'

services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - SERVERURL=my.dyndns.domain
            - SERVERPORT=51820
            - PEERS=peer1,peer2,peer3
            - PEERDNS=XXX.XXX.XXX.XXX
            - INTERNAL_SUBNET=10.13.13.0
            - ALLOWEDIPS=0.0.0.0/0
            - LOG_CONFS=false
        volumes:
            - /path/to/my/local/config:/config
            - /lib/modules:/lib/modules
        ports:
            - 51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: always
```
