### ISSUE TITLE
wg0 interface (client mode) is not created upon container creation

### ISSUE THREAD

**Issue by dgrechka** [linuxserver/docker-wireguard#205]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Since some time ago (weeks?) the ghcr.io/linuxserver/wireguard container stopped to bring the client wg0 interface up upon container start.
A month ago the same setting worked. Something changed with the new version of ghcr.io/linuxserver/wireguard image

------------------------------

## Expected Behavior
When the container starts, the wg0 interface is activated (client mode), the wireguard connection with the server is established

## Current Behavior
The container starts, but the wg0 interface is not created.
w.g. issuing `wg` command shows nothing.
If I attach to the container and run `wg-quick up wg0` manually, the wg0 interface is successfully created, connection is established.

## Steps to Reproduce
1. Create a config map and deplotement by running `kubectl apply -f path_to_deployment.yaml` where path_to_deployment.yaml has content described below.
2. Attach to the container and issue `wg` command
3. Expected: wg0 exists and is up. Actual: wg output is empty. wg0 is not created.

## Environment
**OS:** k3sOS (https://github.com/rancher/k3os)
**CPU architecture:** x86_64
**How docker service was installed:** not a docker, but containerd installed with the OS.

## Command used to create docker container (run/create/compose/screenshot)
K8s deployment config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: wireguard-ruproxy
data:
  wireguard.conf: |
    [Interface]
    Address = 10.0.11.17
    PrivateKey = xxxxxxxxxxxxxxxxxxx
    DNS = 10.0.11.1

    [Peer]
    PublicKey = +Jx+EFRih/nv5pf+TPbQ0wVaz/ptFXFtHkzPNi/B0z4=
    Endpoint = xxxxxxxxxxxxx
    AllowedIPs = 10.0.0.0/20
    PersistentKeepalive = 25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruproxy  
  labels:
    app: ruproxy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ruproxy
  template:
    metadata:
      labels:
        app: ruproxy
    spec:
      containers:
      - name: wireguard
        image: ghcr.io/linuxserver/wireguard
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        volumeMounts:
          - name: wg-config
            mountPath: /config/wg0.conf
            subPath: wireguard.conf
    volumes:
        - name: wg-config
           configMap:
            name: wireguard-ruproxy
```

## Docker logs
```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
Uname info: Linux ruproxy-5b756dd7c6-xfbdb 5.4.0-88-generic #99 SMP Tue Oct 5 16:53:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Client mode selected. ****
chown: changing ownership of '/config/wg0.conf': Read-only file system
s6-rc: warning: unable to start service init-wireguard-confs: command exited 1
```

**Comment by aptalca** [comment]
The log tells you the issue. You need to map `/config` as a folder with write access.

**Comment by dgrechka** [comment]
As it is kubernetes config map, it is mounted as readonly.
I don't think there is a way to mount it writeable, as it is not intended for that.

It is still seem for me as bug, as inability to change permissions/ownership should not break the init process.
Previously that was not the issue, it worked.

**Comment by aptalca** [comment]
We always required the config folder to be mapped as a local writable folder. Read only may have worked in the past, but it was never supported.

K8s supports mapping local folders, block storage like longhorn also works

**Comment by dgrechka** [comment]
Well, `/config` is writable. only `/config/wg0.conf` is not.

Can I somehow force the image to skip the change of file owner? or make it non-critical error if it fails to change the owner?

Does it mean that using k8s config map to hold wg.conf is not intended scenario for  ghcr.io/linuxserver/wireguard image?

I would say it is more natural to hold configuration in ConfigMap rather than building custom docker image or allocate dedicated longhorn filesystem.

**Comment by aptalca** [comment]
> Does it mean that using k8s config map to hold wg.conf is not intended scenario for ghcr.io/linuxserver/wireguard image?

Correct

We don't design our images for that functionality. We design the images to hold all persistent files including config and data in the config folder as a bind mount (with some rare exceptions like nextcloud having two separate mountpoints for config and data)

> Can I somehow force the image to skip the change of file owner? or make it non-critical error if it fails to change the owner?

https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

> I would say it is more natural to hold configuration in ConfigMap rather than building custom docker image or allocate dedicated longhorn filesystem.

Docker is our main supported platform.

**Comment by dgrechka** [comment]
I understand that you have different priorities.
Nevertheless It's a pity that previously the image "just worked" with k8s and configmap, and now it does not.

For those, who still need the k8s + configmap setting, I did the following workaround with init container.
```
initContainers:
- name: init-wireguard
  # the wireguard container wants to change the ownership of wg0.conf file and
  # fails as the file (config map mount) is readonly
  # this init container is workaround. It makes the /config/wg0.conf writable
  image: busybox
  command: ['cp', '/tmp/wg.conf', '/config/wg0.conf']
  volumeMounts:
    - name: shared-config-dir
      mountPath: /config
    - name: wg-config
      mountPath: /tmp/wg.conf
      subPath: wireguard.conf
containers:
- name: wireguard
  image: ghcr.io/linuxserver/wireguard
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
        - SYS_MODULE
    privileged: true
  volumeMounts:
    - name: shared-config-dir
      mountPath: /config
volumes:
- name: wg-config
  configMap:
    name: wireguard-config
- name: shared-config-dir
  emptyDir: {}
```

Although the solution drops everything from `/config` dir except for wg0.conf. Not sure what are the consensuses of that.

@aptalca thanks a lot for such prompt feedback!
you can close the issue if you find this by design. Or you can transform it to "support config map based wg0.conf on k8s" for future, if you find that appropriate.

**Comment by janisii** [comment]
@dgrechka Superb solution! Thank you!

**Comment by JonasJasas** [comment]
Less drama solution:
```yaml
      containers:
        - name: wireguard
          image: linuxserver/wireguard
          securityContext:
            capabilities:
              add:
                - NET_ADMIN

          lifecycle:
            postStart:
              exec:
                command: ['cp', '/tmp/wg0.conf', '/config']

          volumeMounts:
            - name: conf
              mountPath: /tmp/wg0.conf
              subPath: wg0.conf
```
