### ISSUE TITLE
ip6tables-restore: command not found when using alpine image

### ISSUE THREAD

**Issue by user0753** [linuxserver/docker-wireguard#208]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Wireguard tunnel comes up successfully.

## Current Behavior
Errors out after attempting to execute `ip6tables-restore -n` saying command not found. Works as expected when using `latest` image.

## Steps to Reproduce

1. Start container with `alpine` image in client mode

## Environment
**OS:** Ubuntu 22.04.1 LTS
**CPU architecture:** x86_64
**How docker service was installed:** Alpine image from official docker repo via docker-compose.yml

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:alpine
    container_name: wireguard
    networks:
      - wireguardcomms
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - LOCAL_SUBNET=192.168.1.0/24
      - LOCAL_SUBNET_WGSERVER=172.20.0.0/24
    volumes:
      - /home/ubuntu/Docker/wireguard/volumes/config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: 'no'

networks:
  wireguardcomms:
    name: wireguardcomms
    external: true
```

## Docker logs

```
wireguard    | [custom-init] No custom services found, skipping...
wireguard    | [migrations] started
wireguard    | [migrations] no migrations found
wireguard    |
wireguard    | -------------------------------------
wireguard    |           _         ()
wireguard    |          | |  ___   _    __
wireguard    |          | | / __| | |  /  \
wireguard    |          | | \__ \ | | | () |
wireguard    |          |_| |___/ |_|  \__/
wireguard    |
wireguard    |
wireguard    | Brought to you by linuxserver.io
wireguard    | -------------------------------------
wireguard    |
wireguard    | To support the app dev(s) visit:
wireguard    | WireGuard: https://www.wireguard.com/donations/
wireguard    |
wireguard    | To support LSIO projects visit:
wireguard    | https://www.linuxserver.io/donate/
wireguard    | -------------------------------------
wireguard    | GID/UID
wireguard    | -------------------------------------
wireguard    |
wireguard    | User uid:    1000
wireguard    | User gid:    1000
wireguard    | -------------------------------------
wireguard    |
wireguard    | Uname info: Linux d96f81f13fad 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 GNU/Linux
wireguard    | **** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
wireguard    | **** Client mode selected. ****
wireguard    | [custom-init] No custom files found, skipping...
wireguard    | **** Disabling CoreDNS ****
wireguard    | Warning: `/config/wg0.conf' is world accessible
wireguard    | [#] ip link add wg0 type wireguard
wireguard    | [#] wg setconf wg0 /dev/fd/63
wireguard    | [#] ip -4 address add 10.64.154.191/32 dev wg0
wireguard    | [#] ip -6 address add fc00:bbbb:bbbb:bb01::1:9abe/128 dev wg0
wireguard    | [#] ip link set mtu 1420 up dev wg0
wireguard    | [#] resolvconf -a wg0 -m 0 -x
wireguard    | [#] wg set wg0 fwmark 51820
wireguard    | [#] ip -6 route add ::/0 dev wg0 table 51820
wireguard    | [#] ip -6 rule add not fwmark 51820 table 51820
wireguard    | [#] ip -6 rule add table main suppress_prefixlength 0
wireguard    | [#] ip6tables-restore -n
wireguard    | /usr/bin/wg-quick: line 32: ip6tables-restore: command not found
wireguard    | [#] resolvconf -d wg0 -f
wireguard    | [#] ip -6 rule delete table 51820
wireguard    | [#] ip -6 rule delete table main suppress_prefixlength 0
wireguard    | [#] ip link delete dev wg0
wireguard    | s6-rc: warning: unable to start service svc-wireguard: command exited 127
```
