### ISSUE TITLE
[BUG] iptables-legacy not working under Fedora Server with Podman

### ISSUE THREAD

**Issue by jibsaramnim** [linuxserver/docker-wireguard#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Similar to how was described in #223, recent releases of this container fail to work when using Podman on an Fedora Server host, throwing the permission denied error, like so:

```log
iptables v1.8.7 (legacy): can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```

Unlike what was mentioned as the solution in that issue, adding `NET_RAW` does not solve it for me, but switching to an older release from before the switch to `iptables-legacy` does work (`v1.0.20210914-ls82`, in case it helps).

### Steps To Reproduce

1. Launch `:latest` container using podman on Fedora Server (using `sudo`)
2. Wait for container to fail after the iptables steps don't succeed.

### Environment

```markdown
- OS:Fedora 37 Server
- How docker service was installed: `podman` using `dnf`. Latest `podman-compose` devel release [as described here](https://github.com/containers/podman-compose#installation).
```

### CPU architecture

x86-64

### Docker creation

`sudo podman-compose up -d` using the following compose script:

```yaml
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - SERVERURL=x.foo.bar
      - SERVERPORT=51820
      - PEERS=xxx,yyy,zzz
      - PEERDNS=10.0.0.4
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=
      - LOG_CONFS=true
    volumes:
      - ./config:/config:z
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

### Container logs

```log
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=wireguard-server', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_wireguard-server --infra=false --share=
fcbb1fb3274293232495373c6118fde25f2a7506da2821b8aa3208c5210dd6a7
exit code: 0
['podman', 'network', 'exists', 'wireguard-server_default']
podman run --name=wireguard -d --pod=pod_wireguard-server --label io.podman.compose.config-hash=aee9fa65e6519d87b7782387805e74508ce45b73c681e0ad23c5f0399eaf2e7a --label io.podman.compose.project=wireguard-server --label io.podman.compose.version=1.0.4 --label PODMAN_SYSTEMD_UNIT=podman-compose@wireguard-server.service --label com.docker.compose.project=wireguard-server --label com.docker.compose.project.working_dir=/home/davejansen/containers/wireguard-server --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=wireguard --cap-add NET_ADMIN --cap-add NET_RAW -e PUID=1000 -e PGID=1000 -e TZ=Asia/Seoul -e SERVERURL=x.foo.bar -e SERVERPORT=51820 -e PEERS=xxx,yyy,zzz -e PEERDNS=10.0.0.4 -e INTERNAL_SUBNET=10.13.13.0 -e ALLOWEDIPS=0.0.0.0/0 -e PERSISTENTKEEPALIVE_PEERS= -e LOG_CONFS=true -v /home/davejansen/containers/wireguard-server/config:/config:z -v /lib/modules:/lib/modules --net wireguard-server_default --network-alias wireguard -p 51820:51820/udp --sysctl net.ipv4.conf.all.src_valid_mark=1 --restart unless-stopped lscr.io/linuxserver/wireguard:latest
9864f4bf671000fabe91898ecce934a2b3b8a5821d47a2ae30e83c36f7df4520
exit code: 0
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
podman logs -f wireguard
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

Uname info: Linux 9864f4bf6710 6.1.6-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 14 16:55:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Server mode is selected ****
**** External server address is set to x.foo.bar ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0 ****
**** Peer DNS servers will be set to 10.0.0.4 ****
**** Server mode is selected ****
**** No changes to parameters. Existing configs are used. ****
[custom-init] No custom files found, skipping...
.:53
CoreDNS-1.10.0
linux/amd64, go1.19.1, 596a9f9
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.4/32 dev wg0
[#] ip -4 route add 10.13.13.3/32 dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
iptables v1.8.7 (legacy): can't initialize iptables table `filter': Permission denied
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0
s6-rc: warning: unable to start service svc-wireguard: command exited 3
```
