### ISSUE TITLE
[DOC] Adding IPv6 configuration insight

### ISSUE THREAD

**Issue by chadek** [linuxserver/docker-wireguard#233]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to add some details to help user to get IPv6 stack working in this docker container environment with wireguard, the least we can expect for a networking tool. 

I first started to edit the readme-vars.yml file until I discover that an issue is more appropriated for such matter. You will find in the proposed code change the part I intended to update.

I suggest to also provide a docker-compose file example, like the one you already provide in the readme, ready for dual stack (ipv4&ipv6)

### Reason for change

I struggled a bit to get a docker-compose file working using this image with a working IPv6 connectivity. Read-me wasn't helping as it simply suggest to disable IPv6 instead of explaining why or giving any information about IPv6. 

### Proposed code change

Suggest to update the block starting at line 84 with something like this:

 ## Client Mode
  Do not set the `PEERS` environment variable. Drop your client conf into the config folder as `/config/wg0.conf` and start the container.
  # IPv6
  If you get IPv6 related errors in the log and connection cannot be established, edit the `AllowedIPs` line in your peer/client wg0.conf to include only `0.0.0.0/0` and not `::/0`; and restart the container.
  If you want IPv6 working, you can, instead, configure the docker daemon (usely store in /etc/docker/daemon.json) by adding the following options:
  ```
  {
    "ipv6": true,
    "fixed-cidr-v6": "2001:db8:1::/64"
  }
  ```
  Docker daemon must then be restarted to apply changes
  Then docker the docker option `enable_ipv6` must be set to `true` and the following sysctls parameters changes to this values:
  
  ```
  net.ipv6.conf.all.disable_ipv6=0
  net.ipv6.conf.eth0.proxy_ndp=1
  ```

**Comment by chadek** [comment]
To separate a bit, here in a comment the docker-compose file I suggest for a docker daemon configure to support ipv6 interface:


```
version: "2.1"
networks:
  my-custom-network:
    enable_ipv6: true
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.eth0.proxy_ndp=1
    restart: unless-stopped
```
