### ISSUE TITLE
Container doesn't start correctly on Raspberry Pi (1. Generation)

### ISSUE THREAD

**Issue by mhellmeier** [linuxserver/docker-wireguard#25]
## Expected Behavior
Start and run the container correctly for the first time to use wireguard.

## Current Behavior
I just created a `docker-compose.yml` file and started the containers with `docker-compose up`. I only get the following output, nothing more:

```
$ docker-compose up
Starting wireguard ... done
Attaching to wireguard
wireguard    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
wireguard    | [s6-init] ensuring user provided files have correct perms...exited 0.
wireguard    | [fix-attrs.d] applying ownership & permissions fixes...
wireguard    | [fix-attrs.d] done.
wireguard    | [cont-init.d] executing container initialization scripts...
wireguard    | [cont-init.d] 01-envfile: executing... 
wireguard    | [cont-init.d] 01-envfile: exited 267.
wireguard    | [cont-init.d] 10-adduser: executing... 
wireguard    | [cont-init.d] 10-adduser: exited 267.
wireguard    | [cont-init.d] 30-config: executing... 
wireguard    | [cont-init.d] 30-config: exited 267.
wireguard    | [cont-init.d] 99-custom-scripts: executing... 
wireguard    | [cont-init.d] 99-custom-scripts: exited 267.
wireguard    | [cont-init.d] done.
wireguard    | [services.d] starting services
wireguard    | [services.d] done.
```

No QR-code, errors or something like that, the config folder is also empty.

## Steps to Reproduce

1. Create the `docker-compose` file
2. Start it
3. Also tried to install the linux-headers and map the `/usr/src` volume

## Environment
**OS:** Raspbian buster, Release 10
**CPU architecture:** armv6l
**How docker service was installed:**      
Directly

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up`

## Docker logs

Current `docker-compose.yml` file:
```
version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /usr/src:/usr/src
      - /opt/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```
