### ISSUE TITLE
[BUG] internet not available

### ISSUE THREAD

**Issue by Jasonsey** [linuxserver/docker-wireguard#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

this server connect to the router via LAN. And I can connect to the server via iPhone's APP, called wireGuard.

But unfortunately, after this connection established, my phone is no longer able to connect to the internet as well as any device under the router.

### Expected Behavior

what is the correct config to make sure my phone can connect to the internet and also any device under my router

### Steps To Reproduce

 I just start my VPN server using this docker-compose config referring to this repo's homepage:

```yaml
---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

### Environment

```markdown
- OS: ubuntu 22.04
- How docker service was installed: 
   
  
  export DOWNLOAD_URL="https://mirrors.tuna.tsinghua.edu.cn/docker-ce"
  curl -fsSL https://get.docker.com/ | sudo -E sh
```

### CPU architecture

arm64

### Docker creation

```bash
docker-compose up -d
```

### Container logs

```bash
if neccessary, I'll provide it later
```
