### ISSUE TITLE
[BUG] Wireguard Client Not Connecting to Server

### ISSUE THREAD

**Issue by GeneralZero** [linuxserver/docker-wireguard#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am able to get the same configuration to work with Windows and Android clients but doesn't work with Docker Compose. 

Here are no errors in the `docker logs` but no connection is made to the server and no packets can be sent.

### Steps To Reproduce

1. On a Arch running 
2. With this config
```
[...]
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ${CONFIG_FOLDER}/Docker_wg.conf:/config/wg0.conf
      - /usr/src:/usr/src
      - /lib/modules:/lib/modules
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    networks:
      - default
```

4. Error pinging any IP
```
$ sudo docker exec -it wireguard /bin/sh
root@83df6ab844a0:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3110ms
```

### Environment

```markdown
- OS: Arch
- How docker service was installed: through packman
>>> docker version
Client:
 Version:           23.0.3
 API version:       1.41 (downgraded from 1.42)
 Go version:        go1.20.2
 Git commit:        3e7cbfdee1
 Built:             Wed Apr  5 13:17:36 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.2
  Git commit:       3056208812
  Built:            Thu Oct 27 21:29:34 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f.m
 runc:
  Version:          1.1.6
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    967
User GID:    967
───────────────────────────────────────

Uname info: Linux 83df6ab844a0 5.15.77-1-lts #1 SMP Thu, 03 Nov 2022 17:26:01 +0000 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
**** Client mode selected. ****
[custom-init] No custom files found, skipping...
**** Disabling CoreDNS ****
Warning: `/config/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.200.100.4/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] ip -4 route add 128.0.0.0/1 dev wg0
[#] ip -4 route add 0.0.0.0/1 dev wg0
[ls.io-init] done.
```
```
