### ISSUE TITLE
[FEAT] Add optional PEERS_PUBKEYS environment variable 

### ISSUE THREAD

**Issue by pauloromeira** [linuxserver/docker-wireguard#269]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add an optional `PEERS_PUBKEYS` environment variable to pass a comma-separated list of public keys for each peer.

### Reason for change

It is a security concern to have peers private keys stored on the server. Passing public keys would imply that the peers already have their private keys, thus avoiding the need to generate them.

### Proposed code change

Example of `docker-compose.yml`:
```yml
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    environment:
      - PEERS=one,two
      - PEERS_PUBKEYS="JXBI0QKpzdZ/OZDvWK7ec+3E8O6OM6VH2mj6JBVSnX4=,wF/9csR92KkMUacvpP7uGqaaU9vehpUQTveJm9WhQGY="  # optional comma-separated public keys
     
# ...
```

And the generated `peer_one.conf` would be:
```
[Interface]
Address = 10.13.13.2
PrivateKey = <insert_your_private_key_here>
ListenPort = 51820
DNS = 10.13.13.1

# ...
```

PS: I believe comma is not part of possible characters in a public key, but since it has fixed length, the separator can be any.

**Comment by aptalca** [comment]
I'm ok with allowing deletion of private keys of peers, but I'm not in favor of allowing users to define public keys via an env var. They can save it as a file.

**Comment by pauloromeira** [comment]
Hey @aptalca, thanks for your fast reply and feedback!

The benefit of env var is that you can have everything you need inside the `docker-compose.yml`, without the need of any extra files. This is particularly useful if you use a container manager like portainer for spinning up containers.

And if you have the env variable set in your host or use an `.env` file, you can replace your docker-compose.yml to something like this:
```yml
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    environment:
      - PEERS=one,two
      - PEERS_PUBKEYS=$PEERS_PUBKEYS  # optional comma-separated public keys
     
# ...
```

But anyway, this is just personal preference. I'd much appreciate any other way of providing public keys.

Thanks a lot!
