### ISSUE TITLE
[BUG] Modprobe cant find addrtype module

### ISSUE THREAD

**Issue by Ohmslaw79** [linuxserver/docker-wireguard#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I launch the container I get Modprobe errors that are causing the connection to fail

`modprobe: can't change directory to '5.15.0-79-generic': No such file or directory`

I have confirmed that my os does have the addrtype module, but the container does not. It seems that the modprobe command is searching for it within the container, but it is using the path of the host. In the container /lib/modules is completely empty, on the host the addrtype package is in `libs/modules/5.15.0-79-generic`

Here is what I have tried to get access to the addrtype package

1. Attempted to use the --privileged flag
2. Tried loading the xt_addrtype module from within the container using modprobe.
3. Using Docker volumes to load a shell script that ran the modprobe call to load the module.

### Expected Behavior

Modprobe to be able to load the addrtype module and not error out

### Steps To Reproduce

``` INI
[Interface]
PrivateKey = ~redacted~
Address = ~redacted~
DNS = ~redacted~

PostUp = ip6tables -I OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
PostUp = iptables -I OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL ! -d 172.20.0.0/16 -j REJECT
PreDown = ip6tables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
PreDown = iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL ! -d 172.20.0.0/16 -j REJECT

[Peer]
PublicKey = ~redacted~
AllowedIPs = 0.0.0.0/0
Endpoint = ~redacted~
```

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS

- How docker service was installed: using apt-get
```

### CPU architecture

x86-64

### Docker creation

``` YAML
version: "2.1"
services:
  wireguard:
      image: lscr.io/linuxserver/wireguard:latest
      privileged: true
      container_name: wireguard
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        - PUID=1002
        - PGID=1002
        - TZ=Etc/UTC
      volumes:
        - /var/configs/wireguard/config:/config
        - /var/configs/wireguard/modules:/lib/modules
           
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.disable_ipv6=0
      restart: always
      healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 15s
        timeout: 10s
        retries: 6
      networks:
        bridge:
          vpn-network-internal:
          ipv4_address: 172.20.0.3
```

### Container logs

```bash
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Client mode selected. ****
[custom-init] No custom files found, skipping...
**** Disabling CoreDNS ****
Warning: `/config/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add ~redacted~
[#] ip -6 address add ~redacted~
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
s6-rc: fatal: unable to take locks: Resource busy
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
[#] ip6tables -I OUTPUT ! -o wg0 -m mark ! --mark $(wg show wg0 fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
modprobe: can't change directory to '5.15.0-79-generic': No such file or directory
modprobe: can't change directory to '5.15.0-79-generic': No such file or directory
modprobe: can't change directory to '5.15.0-79-generic': No such file or directory
Warning: Extension addrtype is not supported, missing kernel module?
ip6tables v1.8.9 (legacy): Couldn't load match `addrtype':No such file or directory
Try `ip6tables -h' or 'ip6tables --help' for more information.
[#] resolvconf -d wg0 -f
s6-rc: fatal: unable to take locks: Resource busy
[#] iptables-restore -n
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
s6-rc: warning: unable to start service svc-wireguard: command exited 2
```
From what I can tell, modprobe is trying to load the addrtype module, is failing, which is then causing the iptables error which is why its not booting. Also funnily enough, the run I got these logs from was the first run to give me the `Warning: Extension addrtype is not supported, missing kernel module?` line
```
