### ISSUE TITLE
Debian 10. RTNETLINK answers: Operation not supported

### ISSUE THREAD

**Issue by alexanderek** [linuxserver/docker-wireguard#38]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Current Behavior

Docker container errors during start
## Steps to Reproduce

1. Create  docker-compose.yaml
```
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    ports:
      - 52820:51820/udp
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    environment:
      - TZ=Europe/Moscow
      - PUID=1000
      - PGID=1000
      - SERVERURL=[redacted]
      - SERVERPORT=52820
      - PEERS=3
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.14.14.0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
```
2. Run `docker-compose up -d`
3. Run `docker logs -f wireguard`

4. I get errors

```
wireguard    | /etc/kernel/header_postinst.d/dkms:
wireguard    |  * dkms: running auto installation service for kernel 4.19.0-9-amd64
wireguard    |    ...done.
wireguard    | Setting up libdevmapper1.02.1:amd64 (2:1.02.155-3) ...
wireguard    | Setting up grub-common (2.02+dfsg1-20) ...
wireguard    | Setting up dmsetup (2:1.02.155-3) ...
wireguard    | Setting up grub-pc-bin (2.02+dfsg1-20) ...
wireguard    | Setting up grub2-common (2.02+dfsg1-20) ...
wireguard    | Setting up os-prober (1.77) ...
wireguard    | Setting up grub-pc (2.02+dfsg1-20) ...
wireguard    |
wireguard    | Creating config file /etc/default/grub with new version
wireguard    | grub-probe: error: failed to get canonical path of `overlay'.
wireguard    | grub-probe: error: failed to get canonical path of `overlay'.
wireguard    | grub-probe: error: failed to get canonical path of `overlay'.
wireguard    | Processing triggers for libc-bin (2.28-10) ...
wireguard    | Processing triggers for linux-image-5.3.0-1026-gke (5.3.0-1026.28~18.04.1) ...
wireguard    | /etc/kernel/postinst.d/dkms:
wireguard    |  * dkms: running auto installation service for kernel 5.3.0-1026-gke
wireguard    |    ...done.
wireguard    | Server mode is selected
wireguard    | External server address is set to DomainName
wireguard    | External server port is set to 52820. Make sure that port is properly forwarded to port 51820 inside this container
wireguard    | Internal subnet is set to 10.14.14.0
wireguard    | PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.14.14.1 to use wireguard docker host's DNS.
wireguard    | No found wg0.conf found (maybe an initial install), generating 1 server and 3 peer/client confs
wireguard    | PEER 1 QR code:
wireguard    | [cont-init.d] 30-config: exited 0.
wireguard    | [cont-init.d] 99-custom-scripts: executing...
wireguard    | [custom-init] no custom files found exiting...
wireguard    | [cont-init.d] 99-custom-scripts: exited 0.
wireguard    | [cont-init.d] done.
wireguard    | [services.d] starting services
wireguard    | [services.d] done.
wireguard    | [#] ip link add wg0 type wireguard
wireguard    | RTNETLINK answers: Operation not supported
wireguard    | Unable to access interface: Protocol not supported
wireguard    | [#] ip link delete dev wg0
wireguard    | Cannot find device "wg0"
wireguard    | .:53
wireguard    | CoreDNS-1.6.9
wireguard    | linux/amd64, go1.14.1, 1766568
```

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

`uname -a`
`Linux docker-2 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`

`docker -v`
`Docker version 19.03.11, build 42e35e61f3`
## Command used to create docker container (run/create/compose/screenshot)

As above

## Docker logs

As above
