### ISSUE TITLE
Kernel Module not loaded

### ISSUE THREAD

**Issue by nicedevil007** [linuxserver/docker-wireguard#47]
Hey there I'm running a Raspberry Pi 4 with DietPi installed on it.
That is based on debian and it is the 32bit version right now.

While trying to install your docker container via portainer I get this error:

![image](https://user-images.githubusercontent.com/17103076/88505487-e2e81400-cfd7-11ea-87fd-9d9fcb616c9b.png)

here is my stack content to deploy your image:

```
version: "3.7"

volumes:
  config:

services:
  app:
    image: linuxserver/wireguard:arm32v7-latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=testdomain.dedyn.io #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

Am I missing something?
