### ISSUE TITLE
Server port variable not used for interface listen port

### ISSUE THREAD

**Issue by arades79** [linuxserver/docker-wireguard#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The templates included in the image I pulled (using linuxserver/wireguard:latest on both an arm64 device and an amd64 device) have the interface ListenPort hard-coded as 51820, where the endpoint in the peer configuration correctly uses ${SERVERPORT} to use the port defined in the docker-compose.yml

------------------------------

## Expected Behavior
Defining a port with `SERVERPORT: <port>` inside of the docker-compose.yml environment variables will generate configurations using that port as ListenPort in Interface configuration and Endpoint configuration on peers.

## Current Behavior
Defining a non-default port creates a mis-match between Interface and Peer configuration, which prevents a connection from being established.

## Steps to Reproduce

1. pull latest image (as of 07/29)
2. make a docker compose using the template provided in readme
3. change SERVERPORT environment declaration to any unused port other than 51820
4. run the container to generate configuration files
5. inspect <config>/wg0.conf and Interface port will not be the port defined

## Environment
**OS:** Linux (Ubuntu 20.04 and Debian 10)
**CPU architecture:** x86_64/arm64 (arm32 untested)
**How docker service was installed:** included in official repos (Ubuntu) bundled in (linode docker image)

## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yml:
```
version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=America/New_York
      - SERVERURL=li1274-251.members.linode.com
      - SERVERPORT=55555
      - PEERS=1
    ports:
      - 55555:55555/udp
    volumes:
      - ./wireguard_config.d:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - vpn
    restart: unless-stopped
...
```
## Docker logs

N/A
