### ISSUE TITLE
Container exiting with code 128 on server reboot

### ISSUE THREAD

**Issue by tsawhill** [linuxserver/docker-wireguard#73]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Container should be running on reboot

## Current Behavior
I am using this container with `restart: always`, and it always exits on server reboot. I think the error comes from the network not yet being available when the container is started up again, but it does not EVER try to restart. I have to bring it back up manually every time I reboot. I can bring it back up with `docker-compose up` or by restarting the docker daemon.

## Steps to Reproduce

1.Have container running with restart: `always` or `unless-stopped`
2.Restart machine
3.`docker-compose ps`

## Environment
**OS:** Ubuntu Server 18.04
**CPU architecture:** x86_64
**How docker service was installed:** Official docker repo

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up`
```
services:
  vpn:
    image: linuxserver/wireguard
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
     # - SERVERURL=wireguard.domain.com #optional
     # - SERVERPORT=51820 #optional
     # - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/24 #optional
    volumes:
      - ${ROOT}/config/vpn:/config
      - /lib/modules:/lib/modules
    ports:
      - 9091:9091 # port for transmission web UI to be reachable from local network
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
```

## Docker logs

```

vpn            |
vpn            | -------------------------------------
vpn            |           _         ()
vpn            |          | |  ___   _    __
vpn            |          | | / __| | |  /  \
vpn            |          | | \__ \ | | | () |
vpn            |          |_| |___/ |_|  \__/
vpn            |
vpn            |
vpn            | Brought to you by linuxserver.io
vpn            | -------------------------------------
vpn            |
vpn            | To support the app dev(s) visit:
vpn            | WireGuard: https://www.wireguard.com/donations/
vpn            |
vpn            | To support LSIO projects visit:
vpn            | https://www.linuxserver.io/donate/
vpn            | -------------------------------------
vpn            | GID/UID
vpn            | -------------------------------------
vpn            |
vpn            | User uid:    1000
vpn            | User gid:    1000
vpn            | -------------------------------------
vpn            |
vpn            | [cont-init.d] 10-adduser: exited 0.
vpn            | [cont-init.d] 30-config: executing...
vpn            | Uname info: Linux 8c0bb1a30ea2 4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
vpn            | **** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
vpn            | **** Client mode selected.
vpn            | [cont-init.d] 30-config: exited 0.
vpn            | [cont-init.d] 99-custom-scripts: executing...
vpn            | [custom-init] no custom files found exiting...
vpn            | [cont-init.d] 99-custom-scripts: exited 0.
vpn            | [cont-init.d] done.
vpn            | [services.d] starting services
vpn            | [services.d] done.
vpn            | Warning: `/config/wg0.conf' is world accessible
vpn            | [#] ip link add wg0 type wireguard
vpn            | [#] wg setconf wg0 /dev/fd/63
vpn            | [#] ip -4 address add 10.11.4.252/16 dev wg0
vpn            | [#] ip link set mtu 1420 up dev wg0
vpn            | [#] resolvconf -a wg0 -m 0 -x
vpn            | [#] wg set wg0 fwmark 51820
vpn            | [#] ip -6 route add ::/0 dev wg0 table 51820
vpn            | [#] ip -6 rule add not fwmark 51820 table 51820
vpn            | [#] ip -6 rule add table main suppress_prefixlength 0
vpn            | [#] ip6tables-restore -n
vpn            | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
vpn            | [#] ip -4 rule add not fwmark 51820 table 51820
vpn            | [#] ip -4 rule add table main suppress_prefixlength 0
vpn            | [#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
vpn            | sysctl: setting key "net.ipv4.conf.all.src_valid_mark": Read-only file system
vpn            | [#] iptables-restore -n
vpn            | [#] DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route add $HOMENET3 via $DROUTE;ip route add $HOMENET2 via $DROUTE; ip route add $HOMENET via $DROUTE;iptables -I OUTPUT -d $HOMENET -j ACCEPT;iptables -A OUTPUT -d $HOMENET2 -j ACCEPT; iptables -A OUTPUT -d $HOMENET3 -j ACCEPT;  iptables -A OUTPUT ! -o wg0 -m mark ! --mark $(wg show wg0 fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
vpn            | .:53
vpn            | CoreDNS-1.7.1
vpn            | linux/amd64, go1.15.2, aa82ca6
vpn            | Caught SIGTERM signal!
vpn            | [INFO] SIGTERM: Shutting down servers then terminating
vpn            | [cont-finish.d] executing container finish scripts...
vpn            | [cont-finish.d] done.
vpn            | [s6-finish] waiting for services.
vpn            | Warning: `/config/wg0.conf' is world accessible
vpn            | [#] HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route del $HOMENET3 via $DROUTE;ip route del $HOMENET2 via $DROUTE; ip route del $HOMENET via $DROUTE; iptables -D OUTPUT ! -o wg0 -m mark ! --mark $(wg show wg0 fwmark) -m addrtype ! --dst-type LOCAL -j REJECT; iptables -D OUTPUT -d $HOMENET -j ACCEPT; iptables -D OUTPUT -d $HOMENET2 -j ACCEPT; iptables -D OUTPUT -d $HOMENET3 -j ACCEPT
vpn            | Command line is not complete. Try option "help"
vpn            | [s6-finish] sending all processes the TERM signal.
vpn            | [s6-finish] sending all processes the KILL signal and exiting.

```
