### ISSUE TITLE
Cannot generate client conf files

### ISSUE THREAD

**Issue by elclay7** [linuxserver/docker-wireguard#75]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
It is expected that starting the container the configuration file of the users declared in the docker-compose is generated.

## Current Behavior
When starting the container it does not generate the client configuration file in the directory /config.

## Steps to Reproduce

The container starts without problem but I see that it does not generate the configuration file of the only configured client (**PEERS=clay**), I understand that the configuration file should be generated automatically in **/config** but the directory is empty as well as the directory /config/templates

## Environment
**OS:** Raspbian GNU/Linux 10 (buster)
**CPU architecture:** armv7l
**Kernel version** Linux 5.4.72-v7l
**How docker service was installed:** From the distro repo.

## Command used to create docker container (run/create/compose/screenshot)

This is my **docker-compose.yml** 
```
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - SERVERURL=xy.somesite.com
      - SERVERPORT=51820
      - PEERS=clay
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=192.168.0.0/24
    volumes:
      - /mnt/TOSHIBA/WireGuard/config:/config
      - /mnt/TOSHIBA/WireGuard/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

## Docker logs
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux 589854a38033 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l armv7l armv7l GNU/Linux
Error: Unknown device type.
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Kernel headers seem to be present, attempting to build the wireguard module. . . ****
**** Building the module ****
make: Entering directory '/app/wireguard-linux-compat/src'
  Building modules, stage 2.
  MODPOST 1 modules
make: Leaving directory '/app/wireguard-linux-compat/src'
make: Entering directory '/app/wireguard-linux-compat/src'
  INSTALL /app/wireguard-linux-compat/src/wireguard.ko
  DEPMOD  5.4.72-v7l+
Warning: modules_install: missing 'System.map' file. Skipping depmod.
depmod -b "/" -a 5.4.72-v7l+
depmod: WARNING: could not open //lib/modules/5.4.72-v7l+/modules.order: No such file or directory
depmod: WARNING: could not open //lib/modules/5.4.72-v7l+/modules.builtin: No such file or directory
make: Leaving directory '/app/wireguard-linux-compat/src'
**** Let's test our new module. ****
Error: Unknown device type.
**** The module is not active, review the logs. Sleeping now. . . ****
