### ISSUE TITLE
Cannot Start Service On Non-Standard Kernel

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [linuxserver/docker-wireguard#76]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When I create the container in Docker (using the example compose file), the image should download and build and become live 

## Current Behavior

Because I am on a non-standard Kernel (using a VPS that compiles their own Kernel's and don't allow switching to a vanilla one), the container fails to build and I get the following error:

```
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****

**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****
```

## Steps to Reproduce

1. Use VPS (OVH) Running Ubuntu Server 16.04
2. Set Up Container In Docker Compose As Per Instructions
3. Pull And Start The Container

Docker Compose File:

```
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820
#      - PEERS=1 #optional
#      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0
#      - ALLOWEDIPS=192.168.1.0/24,192.168.2.0/24 #optional
    volumes:
      - type: volume
        source: wireguard-config
        target: /config
        read_only: False
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: False
    networks:
      - vpn
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

## Environment
**OS:** Ubuntu Server 16.04 (4.19-ovh-xxxx-std-ipv6-64)
**CPU architecture:** x86_64
**How docker service was installed:** Docker Compose

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
```
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    999
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux c85c57e9187f 4.19-ovh-xxxx-std-ipv6-64 #1454909 SMP Wed Oct 7 08:31:57 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
RTNETLINK answers: Operation not supported
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [18.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [555 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [624 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [12.7 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,130 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,208 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [54.4 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [252 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [301 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [4,358 B]
Get:22 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [13.0 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [337 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,365 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1,781 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [222 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [15.8 kB]
Fetched 36.0 MB in 11s (3,163 kB/s)
Reading package lists...
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****
```
