### ISSUE TITLE
INTERNAL_SUBNET doesn't use mask correctly for generating peer IP addresses

### ISSUE THREAD

**Issue by animal6496** [linuxserver/docker-wireguard#83]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When setting INTERNAL_SUBNET to 172.16.2.128/25 I expected peer addresses to start at 172.16.2.128 (or higher).

## Current Behavior

Generated peer addresses are generated starting at 172.16.2.2.

## Environment
**OS:** Ubuntu 18.04 LTS
**CPU architecture:** x86_64
**How docker service was installed:**

Wireguard service installed using docker compose.
  
## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yml

```
version: '3.2'
services:
  # Wireguard docker container vpn server
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - SERVERURL=myserver.duckdns.org
      - SERVERPORT=51820 
      - PEERS=5
      - PEERDNS=auto                    
      - INTERNAL_SUBNET=172.16.2.128/25
      - ALLOWEDIPS=0.0.0.0/0             
    volumes:
      - type: bind
        source: /pathtodata/wireguard
        target: /config
      - type: bind
        source: /lib/modules
        target: /lib/modules
    ports:
      - target: 51820
        published: 51820
        protocol: udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

## Docker logs

```
.........
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
.:53
CoreDNS-1.8.0
linux/amd64, go1.15.3, 054c9ae
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.16.2.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 172.16.2.6/32 dev wg0
[#] ip -4 route add 172.16.2.5/32 dev wg0
[#] ip -4 route add 172.16.2.4/32 dev wg0
[#] ip -4 route add 172.16.2.3/32 dev wg0
[#] ip -4 route add 172.16.2.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```
