### ISSUE TITLE
Trying to use wireguard with AMI (docker-compose)

### ISSUE THREAD

**Issue by pablolibo** [linuxserver/docker-wireguard#84]
Hi guys,

I am trying to use docker-wireguard on an AWS instance with AMI, (using docker-compose) but I have some problems when trying to start it.

Is it necessary to have debian or ubuntu as OS to be able to start it?

AMI is supported by docker-wireguard?

Any help is welcome

```bash
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Uname info: Linux wireguard-7f7dd84cb8-btmc5 4.14.203-156.332.amzn2.x86_64 #1 SMP Fri Oct 30 19:19:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
RTNETLINK answers: Operation not supported
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [625 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [558 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [12.7 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [18.5 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,132 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,211 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [253 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [54.3 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [4,355 B]
Get:21 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [340 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [13.1 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [302 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [15.8 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1,784 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,368 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [223 kB]
Fetched 36.0 MB in 24s (1,488 kB/s)
Reading package lists...
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****
```

**Comment by aptalca** [comment]
Ubuntu and Debian have the advantage of being able to install kernel headers inside the container during start. If you're using a different OS, you need to manually install the kernel headers on host and map `/usr/src`. It's explained in the readme

**Comment by pablolibo** [comment]
@aptalca, thanks for your reply

I've been installing kernel-devel.x86_64 kernel-headers.x86_64 from yum but I still have the same problem.

Change docker-compose with `/ usr / src /` but still unsuccessful


```yaml
---
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules
      - /usr/src/:/usr/src/
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

from /usr/src and /lib/modules
```bash
[root@ip-10-40-128-127 wireguard]# ls -la /lib/modules
total 8
drwxr-xr-x  3 root root   43 Nov 13 03:34 .
dr-xr-xr-x 22 root root 4096 Dec 10 17:08 ..
drwxr-xr-x  7 root root 4096 Nov 13 03:34 4.14.203-156.332.amzn2.x86_64
[root@ip-10-40-128-127 wireguard]# ls -la /usr/src/
total 0
drwxr-xr-x  4 root root  34 Nov 13 03:33 .
drwxr-xr-x 13 root root 155 Nov 13 03:33 ..
drwxr-xr-x  2 root root   6 Apr  9  2019 debug
drwxr-xr-x  3 root root  43 Dec 10 17:08 kernels
```

Something strange happens when installing kernel-headers.x86_64 the directory it uses is the `/ usr / include`

```bash
[root@ip-10-40-128-127 wireguard]# rpm -ql kernel-headers | head -n 20
/usr/include/asm
/usr/include/asm-generic
/usr/include/asm-generic/auxvec.h
/usr/include/asm-generic/bitsperlong.h
/usr/include/asm-generic/errno-base.h
/usr/include/asm-generic/errno.h
/usr/include/asm-generic/fcntl.h
/usr/include/asm-generic/hugetlb_encode.h
/usr/include/asm-generic/int-l64.h
/usr/include/asm-generic/int-ll64.h
/usr/include/asm-generic/ioctl.h
/usr/include/asm-generic/ioctls.h
/usr/include/asm-generic/ipcbuf.h
/usr/include/asm-generic/kvm_para.h
/usr/include/asm-generic/mman-common.h
/usr/include/asm-generic/mman.h
/usr/include/asm-generic/msgbuf.h
/usr/include/asm-generic/param.h
/usr/include/asm-generic/poll.h
/usr/include/asm-generic/posix_types.h
```
