### ISSUE TITLE
ALLOWEDIPS environment variable has no effect for newly created peers

### ISSUE THREAD

**Issue by P-Takenaka** [linuxserver/docker-wireguard#88]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

The ALLOWEDIPS environment variable should determine the allowed ip range config field of new peers.

## Current Behavior

The allowed ip range for new peers always stays at the default "AllowedIPs = 0.0.0.0/0, ::/0".

## Steps to Reproduce

1. Set ALLOWEDIPS to some ip address range
2. Create new peer config files
3. New peer config files will have default "AllowedIPs = 0.0.0.0/0, ::/0".

## Environment
**OS:** Arch Linux 4.19.0-13-amd64
**CPU architecture:** x86_64
**How docker service was installed:** pacman

## Command used to create docker container (run/create/compose/screenshot)

```
services:
  wireguard:
    image: linuxserver/wireguard:v1.0.20200827-ls7
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='Germany/Frankfurt'
      - SERVERURL=example.com #optional
      - SERVERPORT=65303 #optional
      - PEERS=3 #optional
      - PEERDNS=192.168.1.10 #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=192.168.1.0/24
    volumes:
      - /lib/modules:/lib/modules
    ports:
      - 65303:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```
