### ISSUE TITLE
`wg-quick: line 85: exec: sudo: not found`

### ISSUE THREAD

**Issue by 9SMTM6** [linuxserver/docker-wireguard#91]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Otherwise ignored error on aarch64 (Arch-ARM64): `wg-quick: line 85: exec: sudo: not found`
------------------------------

## Expected Behavior

Be able to connect to the server with a client and use the VPN to access both the general internet as well as local servers

## Current Behavior

I'm perfectly able to scan the QR Codes with my clients, the config in the client seems fine, and when I connect I get no error, but I cant use the internet anymore and I recieve 0 bytes even when trying to use the internet. 

## Steps to Reproduce

1. Install [Manjaro KDE on Raspberry Pi4](https://manjaro.org/download/#raspberry-pi-4-kde-plasma)
2. Install docker-compose etc.
3. Install `wireguard-dkms` kernel-module and for good measure `wireguard-tools` from the manjaro repos (pretty much arch repos) (take note, I did not manually install any `kernel-header` or similar)
4. Start this docker container using (take note of the different mapping for the kernel modules `/usr/lib/modules:/lib/modules`):
```yaml
version: "3.7"
services:
  wireguard:
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    container_name: wireguard
    environment:
      PEERS: phone,ipad,laptop,guest
      PGID: '1000'
      PUID: '1000'
      SERVERPORT: '51820'
      SERVERURL: *********
      TZ: europe/berlin
    image: linuxserver/wireguard # also tried with :v1.0.20200827-ls10
    ports:
    - mode: host
      protocol: udp
      published: 51820
      target: 51820
    restart: unless-stopped
    sysctls:
      net.ipv4.conf.all.src_valid_mark: '1'
    volumes:
    - /**/wireguard:/config:rw
    - /usr/lib/modules:/lib/modules:rw
    - /usr/src:/usr/src:rw
```
5. Try without success to use the VPN
6. Look at log (this is after repeated attempts so no new client configs were generated):
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux 83ca222593cc 5.4.83-1-MANJARO-ARM #1 SMP PREEMPT Mon Dec 14 08:37:33 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Server mode is selected ****
**** External server address is set to 84.130.197.238 ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0, ::/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** Server mode is selected ****
**** No changes to parameters. Existing configs are used. ****
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/usr/bin/wg-quick: line 85: exec: sudo: not found
.:53
CoreDNS-1.8.1
linux/arm64, go1.15.7, 95622f4
```
7. Spot the otherwise easy to overlook error `/usr/bin/wg-quick: line 85: exec: sudo: not found` and wonder whether this is the issue

## Environment
**OS:** Manjaro KDE Raspberry Pi 4
**CPU architecture:** arm64
**How docker service was installed:** see above (hub.docker.com)

## Command used to create docker container (run/create/compose/screenshot)

see above

## Docker logs

see above
